# Generated by Django 2.2.4 on 2020-07-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semirestful_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='desctription',
            new_name='description',
        ),
    ]
